version: '3.8'

services:
  web:
    build:
      context: .              
      dockerfile: Dockerfile  
    container_name: nginx_web_app
    ports:
      - "7777:80"        
    restart: always          
networks:
  proxy:
    external: true